// <auto-generated />
namespace EMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GruposClase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GruposClase));
        
        string IMigrationMetadata.Id
        {
            get { return "201706131028207_GruposClase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
